import { Plus_Jakarta_Sans } from "next/font/google";
import type { Metadata } from "next";
import "../styles/globals.css";
import Navbar from "@/components/Navbar/Navbar";
import { ConfigProvider } from "antd";
import { color } from "@/styles/colors";
import Footer from "@/components/Footer/Footer";
import Contact from "@/app/sections/Contact/Contact";

const plusJakartaSans = Plus_Jakarta_Sans({
  weight: ["200", "400", "600", "800"],
  subsets: ["latin"],
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.variable}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: color.primary,
              fontFamily: `${plusJakartaSans.style.fontFamily}, sans-serif`,
            },
          }}
        >
          <Navbar />
          {children}
          <Contact />
          <Footer />
        </ConfigProvider>
      </body>
    </html>
  );
}
